package GUI;

import civitas.Jugador;
import civitas.CasillaCalle;

import java.util.ArrayList;

/**
 *
 * @author carlosqp
 */
public class JugadorPanel extends javax.swing.JPanel {

    private Jugador jugador;
    
    public void setJugador(Jugador jugador) {
        this.jugador = jugador;

        this.nombreJugador.setText( this.jugador.getNombre() );
        this.saldoJugador.setText( Float.toString( this.jugador.getSaldo() ) );
        this.especuladorJugador.setText( Boolean.toString( this.jugador.esEspeculador() ) );
        
        this.rellenaPropiedades(this.jugador.getPropiedades());
        
        this.repaint();
        this.revalidate();
    }
    
    private void rellenaPropiedades (ArrayList<CasillaCalle> lista) {
        // Se elimina la información antigua
        this.propiedadesPanel.removeAll();
        // Se recorre la lista de propiedades para ir creando sus vistas individuales y añadirlas al panel
        for (CasillaCalle t : lista) {
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            propiedadesPanel.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        // Se fuerza la actualización visual del panel propiedades y del panel del jugador
        repaint();
        revalidate();
    }
    
    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        nombreJugador = new javax.swing.JTextField();
        saldo = new javax.swing.JLabel();
        saldoJugador = new javax.swing.JTextField();
        especulador = new javax.swing.JLabel();
        especuladorJugador = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        propiedadesPanel = new javax.swing.JPanel();
        propiedades = new javax.swing.JLabel();

        titulo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        titulo.setText("Información del Jugador");

        nombre.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        nombre.setText("Nombre:");

        nombreJugador.setEditable(false);
        nombreJugador.setText("jTextField1");
        nombreJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreJugadorActionPerformed(evt);
            }
        });

        saldo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        saldo.setText("Saldo:");

        saldoJugador.setEditable(false);
        saldoJugador.setText("jTextField1");
        saldoJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoJugadorActionPerformed(evt);
            }
        });

        especulador.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        especulador.setText("¿Especulador?:");

        especuladorJugador.setEditable(false);
        especuladorJugador.setText("jTextField1");
        especuladorJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especuladorJugadorActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(propiedadesPanel);

        propiedades.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        propiedades.setText("Propiedades:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre)
                            .addComponent(saldo))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saldoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(especulador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(especuladorJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(propiedades)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldo))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especuladorJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(especulador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(propiedades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreJugadorActionPerformed

    private void especuladorJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especuladorJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especuladorJugadorActionPerformed

    private void saldoJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoJugadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel especulador;
    private javax.swing.JTextField especuladorJugador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreJugador;
    private javax.swing.JLabel propiedades;
    private javax.swing.JPanel propiedadesPanel;
    private javax.swing.JLabel saldo;
    private javax.swing.JTextField saldoJugador;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
