package GUI;

import civitas.CasillaCalle;

/**
 *
 * @author carlosqp
 */
public class PropiedadPanel extends javax.swing.JPanel {

    private CasillaCalle tituloPropiedad;
    
    public void setPropiedad(CasillaCalle tituloPropiedad) {
        this.tituloPropiedad = tituloPropiedad;
        
        this.nombre.setText(this.tituloPropiedad.getNombre());
        this.casas.setText(Integer.toString(this.tituloPropiedad.getNumCasas()));
        this.hoteles.setText(Integer.toString(this.tituloPropiedad.getNumHoteles()));
        this.precioAlquiler.setText(Float.toString(this.tituloPropiedad.getPrecioAlquilerCompleto()));
        this.precioEdificar.setText(Float.toString(this.tituloPropiedad.getPrecioEdificar()));
        
        this.setVisible(true);
        
        
        this.repaint();
        this.revalidate();
    }
    
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        labelCasas = new javax.swing.JLabel();
        casas = new javax.swing.JTextField();
        labelHoteles = new javax.swing.JLabel();
        hoteles = new javax.swing.JTextField();
        labelPrecioAlquiler = new javax.swing.JLabel();
        precioAlquiler = new javax.swing.JTextField();
        labelPrecioEdificar = new javax.swing.JLabel();
        precioEdificar = new javax.swing.JTextField();

        labelNombre.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        labelNombre.setText("Nombre:");

        nombre.setEditable(false);
        nombre.setText("jTextField1");
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        labelCasas.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        labelCasas.setText("Casas:");

        casas.setEditable(false);
        casas.setText("jTextField2");

        labelHoteles.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        labelHoteles.setText("Hoteles:");

        hoteles.setEditable(false);
        hoteles.setText("jTextField3");

        labelPrecioAlquiler.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        labelPrecioAlquiler.setText("Precio Alquiler:");

        precioAlquiler.setEditable(false);
        precioAlquiler.setText("jTextField4");

        labelPrecioEdificar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        labelPrecioEdificar.setText("Precio Edificar:");

        precioEdificar.setEditable(false);
        precioEdificar.setText("jTextField5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCasas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(casas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelHoteles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPrecioAlquiler)
                            .addComponent(labelPrecioEdificar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioEdificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCasas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHoteles)
                    .addComponent(hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecioAlquiler)
                    .addComponent(precioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecioEdificar)
                    .addComponent(precioEdificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField casas;
    private javax.swing.JTextField hoteles;
    private javax.swing.JLabel labelCasas;
    private javax.swing.JLabel labelHoteles;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPrecioAlquiler;
    private javax.swing.JLabel labelPrecioEdificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precioAlquiler;
    private javax.swing.JTextField precioEdificar;
    // End of variables declaration//GEN-END:variables
}
